### ISSUE TITLE
Update HMIS path and filenames

### ISSUE THREAD

**Issue by paulnov** [devdatalab/covid#17]
Proposed name/path changes for HMIS data.

A few universal changes for all datasets we ever work with:
- district_wise -> district
- Never put the word data in a filename— it’s a data file, we know it’s data!
- we don’t need the built/ subfolder— the main folder should have the clean data, and raw data in raw/

For this dataset specifically:
- `nrhm_hmis` -> `hmis` ?  This seems fine since it’s already in the health subfolder
- `lgd_pc11_hmis_district_key.dta` could probably be `hmis_district_key.dta`
- Is there a good reason to store the data across years, like 2013-2014?  I realize this is how it comes raw, and we should keep it that way in the raw folder. But for the clean version, I think it makes a lot more sense to cut it by year. This will take an extra loop at the end but I think it’s worth it as it will make the data easier to use for everyone going forward forever.
- `district_wise_health_data_all.dta` is not a very informative filename when it appears in a dofile. A better and more consistent name with our other stuff would be hmis_clean.dta.  (because we know that hmis only lives at the district, right?

Finally:
- the HMIS cleaning work should be added to `make_covid.do`. Put a commented section with the code necessary to run the next round of the scrape as well— we don't want to rescrape every time we do the make, but we also want the information on how to scrape the next month.

**Comment by kritarth5** [comment]
Hi Paul,

Most of these changes are now made in the `$health/hmis` directory. In particular:

* `nrhm/hmis` -> `hmis`
* `built' subdirectory is gone. So `$health/hmis` now has directories : `raw` `data dictionary` , dta files for each financial year of data, and a `hmis_clean_small.dta` which has select variables across all years.
  * Across years the variables recorded change. Maybe we can do a fuzzy match on the labels followed by a manual check on the variables to check the merge. But for now, because variables change from one financial year to next, they're kept as it is. 
* Additionally, # of hospitals reporting is now merged with the hmis health data for individual years instead of being stored independently in their own .dta file. So now `hmis_dist_clean_`financial_year'` will have both health and hospital data from hmis. 
* I've commented on the keys so Aditi can see it when she's merging lgd keys with this. 
* Added to make_covid.do. However, at this point, we manually download data for 2020-2021(April 2020 onwards), since it has some weird javascript stuff going on that I don't understand. Also, the latest data has been missing since yesterday, perhaps it'll resurface later in the week?
