### ISSUE TITLE
Why do 8 subdistricts have zero CFR predictions?

### ISSUE THREAD

**Issue by paulnov** [devdatalab/covid#9]
CFR prediction is just age multiplied by age-specific mortality. So this should never be zero. But there are 8 subdistricts where it is zero. Why, and what should we do with these?

Can you also take a look at subdistrict 28-544-04870, which has a normal population, but 31% are between age 10-15 and 38% are between age 75-80.  My guess is this subdistrict had a really small SECC population. 

We should probably pick a minimum unit population for age distribution calculations and just make the data missing if there are too few people to get a reasonable guess at the age distribution.

**Comment by alison-campion** [comment]
This issue was coming from missing SECC age data in some of the parsed_draft data files- predominantly in Tamil Nadu where almost every age was missing. The parsed_final versions of these data files did have age, so we switched the ages to be pulled from the parsed_final data and resolved this issue.
